repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-toml

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.11
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: local
      hooks:
          - id: pyright
            name: pyright
            entry: pyright
            language: system
            pass_filenames: false
            always_run: true

    - repo: local
      hooks:
          - id: pytest
            name: pytest
            entry: poetry run pytest
            language: system
            pass_filenames: false
            always_run: true

    - repo: local
      hooks:
          - id: pip-audit
            name: pip-audit
            entry: poetry run pip-audit
            language: system
            pass_filenames: false
            always_run: true

    - repo: https://github.com/PyCQA/bandit
      rev: 1.9.4
      hooks:
          - id: bandit
            args: ['-r', './src', '--severity-level', 'medium']
            pass_filenames: False
